package workspace

var langCommonFile = map[string]string{
	"c++":        "main.cpp",
	"cpp":        "main.cpp",
	"java":       "Main.java",
	"python":     "main.py",
	"python3":    "main.py",
	"c":          "main.c",
	"c#":         "Program.cs",
	"javascript": "index.js",
	"typescript": "index.ts",
	"js":         "index.js",
	"ts":         "index.ts",
	"php":        "index.php",
	"swift":      "main.swift",
	"kotlin":     "Main.kt",
	"dart":       "main.dart",
	"go":         "main.go",
	"golang":     "main.go",
	"ruby":       "main.rb",
	"scala":      "Main.scala",
	"rust":       "main.rs",
	"racket":     "main.rkt",
	"erlang":     "main.erl",
	"elixir":     "main.ex",
}
