name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ${{ matrix.runner_os }}

    strategy:
      matrix:
        include:
          - runner_os: ubuntu-latest
            goos: linux
          - runner_os: macos-latest
            goos: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Run tests
        run: |
          go test -v ./...

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=amd64 go build -o dist/leetx-${{ matrix.goos }}-${{ github.ref_name }} ./cmd/leetx

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/leetx-${{ matrix.goos }}*

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist

      - name: Create release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}